# Spencer Denim Task Manager - Minimal Docker Setup (Services Only)
version: '3.8'

services:
  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: spencer-denim-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # pgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: spencer-denim-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spencerdenim.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
