# Spencer Denim Task Manager - Simple SQLite Local Setup
version: '3.8'

services:
  # Main Application with SQLite
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spencer-taskmanager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=spencer-denim-local-secret-key
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./public:/app/public
      - sqlite_data:/app/sqlite_data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local

networks:
  default:
    name: spencer-network