# Spencer Denim Task Manager - Development Environment (Supabase Version)
version: '3.8'

services:
  # Redis for Caching (Optional - for future scaling)
  redis:
    image: redis:7-alpine
    container_name: spencer-denim-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Next.js Application (Development) - Using Host Network for Supabase Access
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spencer-denim-app
    network_mode: host
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:khabibnurmagomedoV@db.xfzkkmbidevzowixapuh.supabase.co:5432/postgres?sslmode=prefer
      - REDIS_URL=redis://localhost:6379
      - NEXT_TELEMETRY_DISABLED=1
      - NEXTAUTH_SECRET=your-development-secret-key-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
      - APP_NAME=Spencer Denim Task Manager
      - APP_VERSION=1.0.0
      - APP_ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./prisma
          target: /app/prisma
        - action: rebuild
          path: package.json

  # pgAdmin for Database Management (works with Supabase too)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: spencer-denim-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spencerdenim.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
