# Spencer Denim Task Manager - Production Environment

services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: spencer-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Next.js Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spencer-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data_prod:
