# Spencer Denim Task Manager - Development Environment (Supabase)

services:
  redis:
    image: redis:7-alpine
    container_name: spencer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spencer-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - sqlite_data:/app/data
    depends_on:
      - redis

volumes:
  redis_data:
  sqlite_data:
